### ISSUE TITLE
[0] - Product specification page styling

### ISSUE THREAD

**Issue by savagemanage** [mckinley-and-rice/Infogreen-New-Design#18]
# 1 - Left align
# 2 - Center align
# 3 - Center align
![image](https://user-images.githubusercontent.com/44862514/50884074-b2fa0100-139e-11e9-969c-8e21d6c5237d.png)
# 4 - Icon Missing: [Example Item](http://momguide.co.kr/product-details/%EB%B2%84%ED%8B%80%EB%9F%AC%20%EC%9C%A0%EC%95%84%20%EC%84%B8%EC%A0%9C)
![image](https://user-images.githubusercontent.com/44862514/50884189-0704e580-139f-11e9-95bd-5e65786f1f4d.png)

**Comment by sanjeev-sharma** [comment]
Fixed it.
