### ISSUE TITLE
[UI] Company About Page

### ISSUE THREAD

**Issue by savagemanage** [mckinley-and-rice/Infogreen-New-Design#30]
![image](https://user-images.githubusercontent.com/44862514/50900548-5e6c7b00-13ca-11e9-8598-0fb19a4f3435.png)

# Todo
Once a user clicks the button that I highlighted in yellow, he should be prompted with a page that has three tabs.

### Tab 1: About Company Page
If the user clicks the first tab, `tab1_about` must be rendered like the above picture:

### Tab 2 & Tab3
Just like tab 1, render the relevant SVG in the center of the page.

You can find find the svgs here: [SVG for about page.zip](https://github.com/mckinley-and-rice/Infogreen-New-Design/files/2740923/SVG.for.about.page.zip)

**Comment by sanjeev-sharma** [comment]
Completed
